version: '3.8'

services:
  backend:
    build:
      context: ./clay/
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./clay/.env.prod
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./clay/.env.prod

volumes:
  postgres_data_prod: